# Generated by Django 2.2.3 on 2019-10-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformerAuto',
        ),
    ]
