# Generated by Django 2.2.3 on 2019-10-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('user_profile', '0002_delete_performerauto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformerAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('built_year', models.PositiveIntegerField(default=1990, verbose_name='Год выпуска')),
                ('owns_from', models.PositiveIntegerField(verbose_name='В собственности с')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='core.CarBrand', verbose_name='Марка авто')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='core.CarModel', verbose_name='Модель')),
                ('performer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='user_profile.PerformerProfile', verbose_name='Профиль исполнителя')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
    ]
