# Generated by Django 2.2.3 on 2019-10-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20191005_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='performerapproverequest',
            name='was_declined',
            field=models.BooleanField(default=False),
        ),
    ]
