# Generated by Django 2.2.3 on 2019-10-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_performerapproverequest_was_declined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performerauto',
            name='owns_from',
            field=models.PositiveIntegerField(default=1990, verbose_name='В собственности с'),
        ),
    ]
