# Generated by Django 2.2.3 on 2019-09-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Значение тега <title></title>', max_length=500, verbose_name='Заголовок')),
                ('keywords', models.CharField(help_text='Значение аттрибута content тега <meta name="keywords" content="">', max_length=500, verbose_name='Ключевые слова')),
                ('description', models.CharField(help_text='Значение аттрибута content тега <meta name="description" content="">', max_length=1000, verbose_name='Описание')),
            ],
        ),
    ]
