# Generated by Django 2.2.3 on 2019-09-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='header_background',
            field=models.ImageField(default='', upload_to='index/'),
            preserve_default=False,
        ),
    ]
