# Generated by Django 2.2.3 on 2019-09-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0002_indexpage_header_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='description',
            field=models.CharField(blank=True, help_text='Значение аттрибута content тега <meta name="description" content="">', max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='keywords',
            field=models.CharField(blank=True, help_text='Значение аттрибута content тега <meta name="keywords" content="">', max_length=500, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='title',
            field=models.CharField(blank=True, help_text='Значение тега <title></title>', max_length=500, null=True, verbose_name='Заголовок'),
        ),
    ]
