# Generated by Django 2.2.3 on 2019-09-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0003_auto_20190928_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='header_subtagline',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpage',
            name='header_tagline',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
