# Generated by Django 2.2.3 on 2019-09-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0004_auto_20190929_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='about_text',
            field=models.CharField(default='', max_length=1000, verbose_name='Текст о компании'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpage',
            name='company_name',
            field=models.CharField(default='', max_length=250, verbose_name='Название компании'),
            preserve_default=False,
        ),
    ]
