# Generated by Django 2.2.3 on 2019-09-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0005_auto_20190929_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=250, verbose_name='Название шага')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
            ],
        ),
    ]
