# Generated by Django 2.2.3 on 2019-09-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0007_auto_20190929_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingstep',
            options={'ordering': ('order',)},
        ),
    ]
