# Generated by Django 2.2.3 on 2019-10-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0008_auto_20190929_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='email',
            field=models.EmailField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpage',
            name='logo',
            field=models.FileField(default='', upload_to='logo/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpage',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
