# Generated by Django 2.2.3 on 2019-10-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0009_auto_20191017_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='about_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст о компании'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='company_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='header_background',
            field=models.ImageField(blank=True, null=True, upload_to='index/'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='header_subtagline',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='header_tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
