# Generated by Django 2.2.3 on 2019-11-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_performinvitationletterbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformInvitationLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=500)),
                ('message', models.TextField(default='\n        \n    ')),
            ],
        ),
        migrations.DeleteModel(
            name='PerformInvitationLetterBody',
        ),
    ]
