# Generated by Django 2.2.3 on 2019-11-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191110_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performinvitationletter',
            name='message',
            field=models.TextField(default='\n        Уважаемый {performer}!\n\n        Предлагаем Вам пройти выполнить {check}. \n\n        Для детального ознакомления с \n        \n    '),
        ),
    ]
