# Generated by Django 2.2.3 on 2019-12-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191112_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performinvitationletter',
            name='message',
            field=models.TextField(default='\n        Уважаемый {}!\n\n        Предлагаем Вам пройти выполнить {}. \n\n        {} \n\n    '),
        ),
    ]
