# Generated by Django 2.2.3 on 2019-11-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contractsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('short_name', models.CharField(blank=True, max_length=500, null=True)),
                ('INN', models.CharField(blank=True, max_length=50, null=True)),
                ('KPP', models.CharField(blank=True, max_length=50, null=True)),
                ('account', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('bank_BIC', models.CharField(blank=True, max_length=25, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ContractSettings',
        ),
    ]
