# Generated by Django 2.2.3 on 2019-11-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191125_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorganisation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
