# Generated by Django 2.2.3 on 2019-11-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_myorganisation_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('price', models.SmallIntegerField(default=0, verbose_name='Цена')),
            ],
        ),
    ]
