# Generated by Django 2.2.3 on 2019-12-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191201_1448'),
        ('core', '0008_checkkind'),
    ]

    operations = [
    ]
