# Generated by Django 2.2.3 on 2019-12-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20191201_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformerLettersTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_message', models.TextField(default='')),
                ('apply_message', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='PerformInvitationLetter',
        ),
        migrations.AlterField(
            model_name='myorganisation',
            name='INN',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='myorganisation',
            name='KPP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='myorganisation',
            name='account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='myorganisation',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='myorganisation',
            name='bank_BIC',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='БИК банка'),
        ),
        migrations.AlterField(
            model_name='myorganisation',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Расчетный счет банка'),
        ),
        migrations.AlterField(
            model_name='myorganisation',
            name='bank_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название банка'),
        ),
        migrations.AlterField(
            model_name='myorganisation',
            name='full_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='myorganisation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='myorganisation',
            name='short_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Сокращенное название'),
        ),
    ]
