# Generated by Django 2.2.3 on 2019-12-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191201_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performerletterstemplates',
            name='apply_message',
            field=models.TextField(default='Уважаемый, {performer}! \nВас одобрили для проведения проверки {check}.\n{link}'),
        ),
        migrations.AlterField(
            model_name='performerletterstemplates',
            name='invite_message',
            field=models.TextField(default='Уважаемый, {performer}! \nПредлагаем Вам провести {check}.\n{link}'),
        ),
    ]
