# Generated by Django 2.2.3 on 2019-12-23 14:46

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationTreeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название узла')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('full_name', models.CharField(blank=True, help_text='Для отчетов', max_length=1000, null=True, verbose_name='Полное имя')),
                ('checks_theme', models.CharField(blank=True, help_text='Для отчетов', max_length=1000, null=True, verbose_name='Тема проверок')),
                ('contract_name', models.CharField(blank=True, help_text='Для отчетов, Например: Договор № 8/4 – КАН-АВТО от «01» марта 2016 г.', max_length=1000, null=True, verbose_name='Название договора')),
                ('INN', models.CharField(blank=True, help_text='Для отчетов', max_length=1000, null=True, verbose_name='ИНН')),
                ('KPP', models.CharField(blank=True, help_text='Для отчетов', max_length=1000, null=True, verbose_name='КПП')),
                ('legal_address', models.CharField(blank=True, help_text='Для отчетов', max_length=1000, null=True, verbose_name='Юридический адрес')),
                ('docs_generating_type', models.CharField(choices=[('full', 'Общий'), ('by department', 'По подразделениям')], default='full', max_length=30, verbose_name='Тип генерации документов')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.City', verbose_name='Город')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organisation_tree.OrganisationTreeNode')),
            ],
            options={
                'verbose_name': 'Организации',
                'verbose_name_plural': 'Организациии',
            },
        ),
        migrations.CreateModel(
            name='OrganisationMonthlyDocumentStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_storages', to='organisation_tree.OrganisationTreeNode')),
            ],
            options={
                'ordering': ('date',),
                'unique_together': {('organisation', 'date')},
            },
        ),
        migrations.CreateModel(
            name='OrganisationDocumentsContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.FilePathField(blank=True, max_length=250, null=True, path='/home/nasirovsultan/PycharmProjects/ghost_shopper/media/docs/')),
                ('payment', models.FilePathField(blank=True, max_length=250, null=True, path='/home/nasirovsultan/PycharmProjects/ghost_shopper/media/docs/')),
                ('organisation_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation_tree.OrganisationTreeNode')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organisation_tree.OrganisationMonthlyDocumentStorage')),
            ],
            options={
                'unique_together': {('storage', 'organisation_node')},
            },
        ),
    ]
