# Generated by Django 2.2.3 on 2019-11-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_tree', '0002_auto_20191124_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.FileField(upload_to='organisation/agreements/')),
                ('payment', models.FileField(upload_to='organisation/payments/')),
                ('created', models.DateField()),
            ],
        ),
    ]
