# Generated by Django 2.2.3 on 2019-11-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_tree', '0003_organisationdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisationdocument',
            old_name='created',
            new_name='date',
        ),
        migrations.AddField(
            model_name='organisationdocument',
            name='organisation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='organisation_tree.OrganisationTreeNode'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='organisationdocument',
            unique_together={('organisation', 'date')},
        ),
    ]
