# Generated by Django 2.2.3 on 2019-11-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_tree', '0005_auto_20191124_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationdocument',
            name='agreement',
            field=models.FilePathField(path='/home/nasirovsultan/PycharmProjects/ghost_shopper/media/docs/'),
        ),
        migrations.AlterField(
            model_name='organisationdocument',
            name='payment',
            field=models.FilePathField(path='/home/nasirovsultan/PycharmProjects/ghost_shopper/media/docs/'),
        ),
    ]
