# Generated by Django 2.2.3 on 2019-11-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_tree', '0006_auto_20191124_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationdocument',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='organisationdocument',
            name='agreement',
            field=models.FilePathField(max_length=250, path='/home/nasirovsultan/PycharmProjects/ghost_shopper/media/docs/'),
        ),
        migrations.AlterField(
            model_name='organisationdocument',
            name='payment',
            field=models.FilePathField(max_length=250, path='/home/nasirovsultan/PycharmProjects/ghost_shopper/media/docs/'),
        ),
    ]
