# Generated by Django 2.2.3 on 2019-11-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_tree', '0007_auto_20191125_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationtreenode',
            name='contract_name',
            field=models.CharField(blank=True, help_text='Для отчетов, Например: Договор № 8/4 – КАН-АВТО от «01» марта 2016 г.', max_length=1000, null=True, verbose_name='Название договора'),
        ),
    ]
