# Generated by Django 2.2.3 on 2019-11-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_tree', '0008_auto_20191126_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationdocument',
            name='agreement',
            field=models.FilePathField(blank=True, max_length=250, null=True, path='/home/nasirovsultan/PycharmProjects/ghost_shopper/media/docs/'),
        ),
        migrations.AlterField(
            model_name='organisationdocument',
            name='payment',
            field=models.FilePathField(blank=True, max_length=250, null=True, path='/home/nasirovsultan/PycharmProjects/ghost_shopper/media/docs/'),
        ),
    ]
