# Generated by Django 2.2.3 on 2019-12-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_tree', '0009_auto_20191130_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationtreenode',
            name='docs_generating_type',
            field=models.CharField(choices=[('full', 'Общий'), ('by_department', 'Для отделений')], default='full', max_length=30, verbose_name='Тип генерации документов'),
        ),
    ]
