# Generated by Django 2.2.3 on 2019-12-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_tree', '0010_organisationtreenode_docs_generating_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationtreenode',
            name='docs_generating_type',
            field=models.CharField(choices=[('full', 'Общий'), ('by department', 'По подразделениям')], default='full', max_length=30, verbose_name='Тип генерации документов'),
        ),
    ]
