# Generated by Django 2.2.3 on 2019-12-21 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_tree', '0013_auto_20191222_0202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organisationdocumentscontainer',
            unique_together={('storage', 'organisation_node')},
        ),
    ]
