# Generated by Django 2.2.3 on 2019-12-23 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип')),
                ('audio', models.FileField(blank=True, null=True, upload_to='checklist_audio/', verbose_name='Аудиозапись')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='Дата визита')),
                ('check_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='check.Check', verbose_name='Проверка')),
            ],
            options={
                'verbose_name': 'чеклист',
                'verbose_name_plural': 'чеклисты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('text', models.CharField(max_length=1500, verbose_name='Текст Вопроса')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, unique=True, verbose_name='Название секции')),
            ],
            options={
                'verbose_name': 'название секции',
                'verbose_name_plural': 'названия секций',
            },
        ),
        migrations.CreateModel(
            name='TextQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('value', models.CharField(max_length=150, verbose_name='Значение')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_options', to='checklist.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Текстовый вариант',
                'verbose_name_plural': 'Текстовые варианты',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextChoicesAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий испольнителя')),
                ('appeal_comment', models.TextField(blank=True, null=True, verbose_name='Текст апелляции')),
                ('appeal_answer', models.TextField(blank=True, null=True, verbose_name='Ответ на аппеляцию')),
                ('answer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklist.TextQuestionOption', verbose_name='Ответ')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_choices_answer', to='checklist.Question')),
            ],
            options={
                'verbose_name': 'Ответ с текстовыми вариантами',
                'verbose_name_plural': 'Ответы с текстовыми вариантами',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='checklist.Checklist', verbose_name='Чеклист')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='checklist.SectionName', verbose_name='Название секции')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='checklist.Section', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'секция',
                'verbose_name_plural': 'секции',
                'ordering': ('order',),
                'abstract': False,
                'unique_together': {('checklist', 'name')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='checklist.Section', verbose_name='Секция'),
        ),
        migrations.CreateModel(
            name='OpenAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий испольнителя')),
                ('appeal_comment', models.TextField(blank=True, null=True, verbose_name='Текст апелляции')),
                ('appeal_answer', models.TextField(blank=True, null=True, verbose_name='Ответ на аппеляцию')),
                ('answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответ')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='open_answer', to='checklist.Question')),
            ],
            options={
                'verbose_name': 'Открытый ответ',
                'verbose_name_plural': 'Открытые ответы',
            },
        ),
        migrations.CreateModel(
            name='IntegerQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Значение')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='Баллов')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_options', to='checklist.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Числовой вариант',
                'verbose_name_plural': 'Числовые варианты',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegerChoicesAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий испольнителя')),
                ('appeal_comment', models.TextField(blank=True, null=True, verbose_name='Текст апелляции')),
                ('appeal_answer', models.TextField(blank=True, null=True, verbose_name='Ответ на аппеляцию')),
                ('answer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklist.IntegerQuestionOption', verbose_name='Ответ')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='int_choices_answer', to='checklist.Question')),
            ],
            options={
                'verbose_name': 'Ответ с числовыми вариантами',
                'verbose_name_plural': 'Ответы с числовыми вариантами',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='checklist_images/', verbose_name='Изображение')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='checklist.Checklist', verbose_name='Чеклист')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='GeneralAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий испольнителя')),
                ('appeal_comment', models.TextField(blank=True, null=True, verbose_name='Текст апелляции')),
                ('appeal_answer', models.TextField(blank=True, null=True, verbose_name='Ответ на аппеляцию')),
                ('answer', models.NullBooleanField(default=None, verbose_name='Ответ')),
                ('positive_answer_value', models.PositiveSmallIntegerField(default=1, verbose_name='Баллов за положительный ответ')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_answer', to='checklist.Question')),
            ],
            options={
                'verbose_name': 'Общий ответ',
                'verbose_name_plural': 'Общие ответы',
            },
        ),
    ]
