# Generated by Django 2.2.3 on 2019-10-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionname',
            name='value',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название секции'),
        ),
    ]
