# Generated by Django 2.2.3 on 2019-10-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20191030_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='new_audio/')),
                ('checklist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_file', to='checklist.Checklist', verbose_name='Чеклист')),
            ],
        ),
    ]
