# Generated by Django 2.2.3 on 2019-10-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_checklistaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistaudio',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='new_audio/'),
        ),
    ]
