# Generated by Django 2.2.3 on 2019-10-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_auto_20191031_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChecklistAudio',
        ),
    ]
