# Generated by Django 2.2.3 on 2019-11-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_delete_checklistaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
