# Generated by Django 2.2.3 on 2019-11-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_checklist_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='excel_file',
            field=models.FileField(default='', upload_to='', verbose_name='checklist_excel/'),
            preserve_default=False,
        ),
    ]
