# Generated by Django 2.2.3 on 2019-11-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_checklist_excel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='excel_file',
            field=models.FilePathField(default=''),
        ),
    ]
