# Generated by Django 2.2.3 on 2019-11-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_auto_20191113_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='excel_file',
        ),
        migrations.AddField(
            model_name='checklist',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата визита'),
        ),
    ]
