# Generated by Django 2.2.3 on 2019-12-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0010_auto_20191127_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=1500, verbose_name='Текст Вопроса'),
        ),
    ]
