# Generated by Django 2.2.3 on 2019-09-28 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Создана'), ('AVAILABLE', 'Доступна'), ('PROCESSING', 'В работе'), ('FILLED', 'Проверка'), ('CONFORMATION', 'Одобрение'), ('APPEAL', 'Аппеляция'), ('CLOSED', 'Закрыта')], default='CREATED', max_length=30, verbose_name='Статус')),
                ('type', models.CharField(choices=[('TEMPLATE', 'Шаблон'), ('USUAL', 'Обычная')], default='Обычная', max_length=20, verbose_name='Тип')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('performer_typed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Исполнитель(ФИО)')),
                ('reward', models.PositiveSmallIntegerField(default=0, verbose_name='Награда(руб.)')),
                ('was_sent_to_rework', models.BooleanField(default=False, verbose_name='Была отправлена на доработку')),
                ('was_appealed', models.BooleanField(default=False, verbose_name='Была аппеляция')),
                ('conformation_period', models.PositiveSmallIntegerField(default=1, verbose_name='Дней на аппеляцию')),
                ('reappeal_period', models.PositiveSmallIntegerField(default=1, verbose_name='Дней на повторную аппеляцию')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Проверка',
                'verbose_name_plural': 'Проверки',
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='CheckPerformRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perform_requests', to='check.Check')),
            ],
        ),
    ]
