# Generated by Django 2.2.3 on 2019-09-28 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation_tree', '0001_initial'),
        ('project', '0001_initial'),
        ('instruction', '0001_initial'),
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkperformrequest',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perform_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='check',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.AddField(
            model_name='check',
            name='instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruction.Instruction', verbose_name='Инструкция'),
        ),
        migrations.AddField(
            model_name='check',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performer', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='check',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_obj', to='project.Project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='check',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation_tree.OrganisationTreeNode', verbose_name='Цель'),
        ),
        migrations.AlterUniqueTogether(
            name='checkperformrequest',
            unique_together={('check_obj', 'performer')},
        ),
    ]
