# Generated by Django 2.2.3 on 2019-09-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20190928_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='deadline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='check',
            name='start_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата начала'),
        ),
    ]
