# Generated by Django 2.2.3 on 2019-11-10 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('check', '0004_auto_20190929_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPerformInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perform_invitations', to='check.Check')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perform_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('check_obj', 'performer')},
            },
        ),
    ]
