# Generated by Django 2.2.3 on 2019-11-26 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0006_checkkind'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='check.CheckKind'),
        ),
        migrations.AddField(
            model_name='check',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата визита'),
        ),
    ]
