# Generated by Django 2.2.3 on 2019-11-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0007_auto_20191126_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='kind',
        ),
        migrations.DeleteModel(
            name='CheckKind',
        ),
    ]
