# Generated by Django 2.2.3 on 2019-11-26 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_checkkind'),
        ('check', '0008_auto_20191126_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CheckKind'),
        ),
    ]
