# Generated by Django 2.2.3 on 2019-11-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0009_check_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='visit_date',
        ),
    ]
