# Generated by Django 2.2.3 on 2019-12-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0010_remove_check_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='appealed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='sent_for_conformation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
