# Generated by Django 2.2.3 on 2019-12-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0011_auto_20191206_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='appealed_date',
        ),
        migrations.RemoveField(
            model_name='check',
            name='reappeal_period',
        ),
    ]
