# Generated by Django 2.2.3 on 2019-10-14 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_chat', '0003_auto_20191001_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagecomment',
            options={},
        ),
        migrations.AlterField(
            model_name='messagecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagecomment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation_chat.Message'),
        ),
    ]
