# Generated by Django 2.2.3 on 2019-10-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_chat', '0004_auto_20191014_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecomment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='organisation_chat.Message'),
        ),
    ]
